services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.render
    container_name: force-gym-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://roundhouse.proxy.rlwy.net:34284/railway
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: WRXGrpzusamYUjVRHDbTEQuBdcCRCjGY
      FORCE_GYM_JWT_SECRET: "0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF"
