services:
  - type: web
    name: force-gym-monolith
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: FORCE_GYM_JWT_SECRET
        generateValue: true
    healthCheckPath: /actuator/health
