services:
  postgres:
    image: postgres:16-alpine
    container_name: force-gym-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: forcegym_next
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tilin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/postgresql:/docker-entrypoint-initdb.d

volumes:
  postgres_data: