server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: service-rutinas
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/forcegym_next}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:tilin}

management:
  endpoints:
    web:
      exposure:
        include: health,info